package com.forketyfork.codingproblems;

import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.*;

class SubstringWithConcatenationOfAllWordsTest {

    private record TestCase(String s, String[] words, List<Integer> expected) {

    }

    @ParameterizedTest
    @MethodSource("source")
    void test(SubstringWithConcatenationOfAllWordsTest.TestCase testCase) {
        assertEquals(testCase.expected,
                new SubstringWithConcatenationOfAllWords().findSubstring(testCase.s, testCase.words));
    }

    public static Stream<SubstringWithConcatenationOfAllWordsTest.TestCase> source() {
        return Stream.of(
                new SubstringWithConcatenationOfAllWordsTest.TestCase( // 6996 characters
                        "ejwwmybnorgshugzmoxopwuvshlcwasclobxmckcvtxfndeztdqiakfusswqsovdfwatanwxgtctyjvsmlcoxijrahivwfybbbudosawnfpmomgczirzscqvlaqhfqkithlhbodptvdhjljltckogcjsdbbktotnxgwyuapnxuwgfirbmdrvgapldsvwgqjfxggtixjhshnzphcemtzsvodygbxpriwqockyavfscvtsewyqpxlnnqnvrkmjtjbjllilinflkbfoxdhocsbpirmcbznuioevcojkdqvoraeqdlhffkwqbjsdkfxstdpxryixrdligpzldgtiqryuasxmxwgtcwsvwasngdwovxzafuixmjrobqbbnhwpdokcpfpxinlfmkfrfqrtzkhabidqszhxorzfypcjcnopzwigmbznmjnpttflsmjifknezrneedvgzfmnhoavxqksjreddpmibbodtbhzfehgluuukupjmbbvshzxyniaowdjamlfssndojyyephstlonsplrettspwepipwcjmfyvfybxiuqtkdlzqedjxxbvdsfurhedneauccrkyjfiptjfxmpxlssrkyldfriuvjranikluqtjjcoiqffdxaukagphzycvjtvwdhhxzagkevvuccxccuoccdkbboymjtimdrmerspxpktsmrwrlkvpnhqrvpdekmtpdfuxzjwpvqjjhfaupylefbvbsbhdncsshmrhxoyuejenqgjheulkxjnqkwvzznriclrbzryfaeuqkfxrbldyusoeoldpbwadhrgijeplijcvqbormrqglgmzsprtmryvkeevlthvflsvognbxfjilwkdndyzwwxgdbeqwlldyezmkopktzugxgkklimhhjqkmuaifnodtpredhqygmedtqpezboimeuyyujfjxkdmbjpizpqltvgknnlodtbhnbhjkmuhwxvzgmkhbcvvadhnssbvneecglnqxhavhvxpkjxlluilzpysjcnwguyofnhfvhaceztoiscumkhociglkvispihvyoatxcxbeqsmluixgsliatukrecgoldmzfhwkgaqzsckonjuhxdhqztjfxstjvikdrhpyjfxbjjryslfpqoiphrwfjqqhaamrjbrsiovrxmqsyxhqmritjeauwqbwtpqcqhvyyssvfknfhxvtodpzipueixdbntdfcaeatyyainfpkclbgaaqrwwzwbcjwiqzkwzfuxfclmsxpdyvfbnwxjytnaejivivriamhgqsskqhnqeurttrfrmstrbeokzhuzvbfmwywohmgogyhzpmsdemugqkspsmoppwbnwabdmiruibwznqcuczculujfiavzwynsyqxmarjkshjhxobandwyzggjibjgzyaaqxorqxbkenscbveqbaociwmqxxyzvyblypeongzrttvwqzmrccwkzidyfbxcaypyquodcpwxkstbthuvjqgialhfmgjohzoxvdaxuywfqrgmyahhtpqtazbphmfoluliznftodyguesshcacrsvutylalqrykehjuofisdookjhrljvedsywrlyccpaowjaqyfaqioesxnlkwgpbznzszyudpwrlgrdgwdyhucztsneqttsuirmjriohhgunzatyfrfzvgvptbgpwajgtysligupoqeoqxoyqtzozufvvlktnvahvsseymtpeyfvxttqosgpplkmxwgmsgtpantazppgnubmpwcdqkvhwfuvcahwibniohiqyywnuzzmxeppokxksrfwrpuzqhjgqryorwboxdauhrkxehiwaputeouwxdfoudcoagcxjcuqvenznxxnprgvhasffxtzaxpcfrcovwgrcwqptoekhmgpoywtxruxokcubekzcrqengviwbtgnzvdzrwwkqvacxwgdhffyvjldgvchoiwnfzoyvkiogisdfyjmfomcazigukqlumyzmnzjzhzfpslwsukykwckvktswjdqxdrlsqvsxwxpqkljeyjpulbswwmuhplfueqnvnhukgjarxlxvwmriqjgmxawmndhsvwnjdjvjtxcsjapfogpesxtpypenunfpjuyoevzztctecilqqbxkaqcyhiobvtqgqruumvvhxolbyzsqcrdchhdqprtkkjsccowrjtyjjmkhleanvfpemuublnnyzfabtxsestncfalqenfcswgerbfcqsapzdtscnzugmwlmidtxkvqhbuaecevwhmwkfqmvpgbefpqpsjmdecmixmmbsjxzwvjdmxydechlraajjmoqpcyoqmrjwoiumuzatydzcnktnkeyztoqvogodxxznhvzduzxudwwqhpftwdspuimioanlzobhjakgajafgzxpqckmhdbbnqmcszpuoqbztnftzgahhxwxbgkilnmzfydyxusnnvngksbjabqjaohdvrniezhmxmkxhemwbbclwdxwgngicplzgajmaryzfkyoqlkrmmfirchzrphveuwmvgaxzbwenvteifxuuefnimnadwxhruvoavlzyhfmeasmgrjawongccgfbgoualiaivbhcgvjjnxpggrewglalthmzvgziobrjeanlvyukwlscexbkibvdjhdgnepdiimmkcxhattwglbkicvsfswocbvphmtpwhcgjbnmxgidtlqcnnwtfujhvgzdussqbwynylzvtjapvqtidpdjkpshvrmqlhindhabubyokzdfrwqvnvgzkyhistydagsgnujiviyijdnabfxqbdqnexvwsvzvcsbrmkbkuzsdehghndyqjodnnblfwmaygdstotfkvxozgwhtbhlkvrzismnozqpfthajafuxekzlgigjpsukjvsdihrjzgovnreqwapdkoqswyclqyvbvpedzyoyedvuuamscbxnqnfmmjyehvidnoimmxmtcinwkbqmcobubjjpshucechrqrffqsyscnqoohcsxenypyqhfklloudgmklcejvgynwouzhtfwuuukdbwpmkjrqxeeaipxrokncholathupdetgaktmvmftqjvzyssocftjwemroghrncynmtchhhcaqxbqpthuaafwgrouaxonzocljeuslzsdwvuoodipdpnlhdihaywzmymxdjrqikughquwtenyucjdgrmipiidiwclhuepgyynoslhzahtdqwliktzsddaahohbszhqxxgripqlwlomjbwtuynydoakejmwkvojuwbfltqjfgxqhwkduzbxpdhtpvrzrfjndmsqfizmqxdxtpbpoemekvxzrrakwjxcxqsdasptruqmjtbaapgmkfnbwnlvzlxwdpzfjryanrmzmpzoefapmnsjdgecrdywsabctaegttffigupnwgakylngrrxurtotxqmzxvsqazajvrwsxyeyjteakeudzjxwbjvagnsjntskmocmpgkybqbnwvrwgoskzqkgffpsyhfmxhymqinrbohxlytsmoeleqrjvievpjipsgdkrqeuglrsjnmvdsihicsgkybcjltcswolpsfxdypmlbjotuxewskisnmczfgreuevnjssjifvlqlhkllifxrxkdbjlhcpegmtrelbosyajljvwwedtxbdccpnmreqaqjrxwulpunagwxesbilalrdniqbzxrbpcvmzpyqklsskpwctgqtrjwhrpisocwderqfiqxsdpkphjsapkvhvsqojyixaechvuoemmyqdlfkuzmlliugckuljfkljoshjhlvvlnywvjswvekfyqhjnsusefdtakejxbejrchoncklguqgnyrcslwztbstmycjziuskegagtlonducdogwbevugppsptdqbajmepmmizaycwcgmjeopbivsyphtvxvvgjbyxpgwpganjiaumojpyhhywosrmnouwpstgbrvhtlqcnmqbygbfnabesvshjmdbhyhirfrkqkmfwdgujhzyjdcbyuijjnkqluaczrnrbbwaeeupnwqzbsazplkyaxqorqsshhlljjlpphhedxdepgfgrqerpuhgmaawhnhqwsgnznrfmxjbdrkwjopylxezxgvetcvrwdewsxdeumhzfrvoilmvksuhyqltuimrnsphqslmgvmmojawwptghonigbdclqtbikiacwpjrbxhmzejozpypfixglatdvuogdoizdtsgsztsfcihtgwyqugeuahpuvvzmgarbsyuutmbxuisdfrvbxzxzhmuektssuktoknkfbmcwwubbnwenybmfqglaceuyqnoadzfenjcjfdlvcpiatuhjdujhaffqsvqvuxchgerokejovrqonxxstibunikiedfyahijobxyhimebctobsjudkqstbcxgixgrhpfiofpwruzvpqyjzvollheoldutddnksutjakhtghpxxnjykxjwgqmsvhnykclexepxqxqzghwfxfdhfmflesfabvanxlrurjtigkjotftqnwyskffpxlragrnfffawqtgyfpmzxfpkdpenxlewyxxgrkmwrmshhzfnorolyfxbvdrspxqnxnuoygkruczddgssygfymdcjgvdxutlrhffhnpyjuxmxefrelxezcgikdliyhvpocvvpkvagvmezrxffujeysplvavtjqjxsgujqsjznxforctwzecxyrkwufpdxadrgzczrnyelfschnagucguuqqqwitviynrypsrdswqxqsegulcwrwsjnihxedfcqychqumiscfkwmqqxunqrfbgqjdwmkyelbldxympctbzfupeocwhkypchuyvhybsbmvymjppfrqmlfrbkpjwpyyytytawuuyjrwxboogfessmltwdcssdqtwomymjskujjtmxiueopwacrwfuqazitvyhvlspvoaeipdsjhgyfjbxhityisidnhlksfznubucqxwaheamndjxmcxwufajmnveuwuoyosqnoqwvtjkwuhkzghvmjhawcfszbhzrbpgsidnbmxxihihnrfbamcyojqpkzodbejtmmipahojoysepzhpljpaugrghgjimtdahnpivdtlcnptnxjyiaafislqavamqgmxtdfoiaakorebqpbbpegawrqymqkewycsdjglkiwaacdqterkixkgraedtqirqmjtvsfhadhafktyrmkzmvidxmisfskvevpcnujqxrqedleuyowkjgphsxzzqlvujkwwgiodbfjesnbsbzcnftuzrvzjjudsgcqmmfpnmyrenuxotbbyvxyovzxgtcyzgqnsvcfhczoptnfnojnlinbfmylhdlijcvcxzjhdixuckaralemvsnbgooorayceuedtomzyjtctvtwgyiesxhynvogxnjdjphcftbefxgasawzagfugmuthjahylkhatlgpnkuksuesrduxkodwjzgubpsmzzmvkskzeglxaqrrvmrgcwcnvkhwzbibaxwnriowoavosminabvfxastkcrkdclgzjvqrjofjjvbyfragofeoazzeqljuypthkmywaffmcjkickqqsuhsviyovhitxeajqahshpejaqtcdkuvgdpclnsguabtgbfwdmrmbvydorfrbcokfdmtsgboidkpgpnmdeyhawkqqshtwxdbarwuxykgduxjlkxppwyruihkcqgynjcpbylayvgdqfpbqmshksyfbhrfxxemhgbkgmkhjtkzyzdqmxxwqvdtevyducpdksntgyaqtkrrkwiyuhukfadjvdnrievszilfinxbyrvknfihmetreydbcstkwoexwsfhfekfvfplmxszcosgovisnbemrjlndqwkvhqsofdbdychmupcsxvhazvrihhnxfyumonbvqeyoghccxfuwacxzxqkezxefxarnnujgyjugrzjoefmghjfhcrnbrtgouaehwnnxwkdplodpuqxdbemfwahptpfppjzowoltyqijfoabgzejerpatwponuefgdtcrgxswiddygeeflpjeelzccnsztxfyqhqyhkuppapvgvdtkmxraytcolbhkiiasaazkvqzvfxbaaxkoudovxrjkusxdazxaawmvoostlvvnsfbpjqkijvudpriqrfsrdfortimgdhtypunakzituezjyhbrpuksbamuiycngvlvpyvczfxvlwhjgicvempfobbwadkiavdswyuxdttoqaaykctprkwfmyeodowglzyjzuhencufcwdobydslazxadnftllhmjslfbrtdlahkgwlebdpdeofidldoymakfnpgekmsltcrrnxvspywfggjrmxryybdltmsfykstmlnzjitaipfoyohkmzimcozxardydxtpjgquoluzbznzqvlewtqyhryjldjoadgjlyfckzbnbootlzxhupieggntjxilcqxnocpyesnhjbauaxcvmkzusmodlyonoldequfunsbwudquaurogsiyhydswsimflrvfwruouskxjfzfynmrymyyqsvkajpnanvyepnzixyteyafnmwnbwmtojdpsucthxtopgpxgnsmnsrdhpskledapiricvdmtwaifrhnebzuttzckroywranbrvgmashxurelyrrbslxnmzyeowchwpjplrdnjlkfcoqdhheavbnhdlltjpahflwscafnnsspikuqszqpcdyfrkaabdigogatgiitadlinfyhgowjuvqlhrniuvrketfmboibttkgakohbmsvhigqztbvrsgxlnjndrqwmcdnntwofojpyrhamivfcdcotodwhvtuyyjlthbaxmrvfzxrhvzkydartfqbalxyjilepmemawjfxhzecyqcdswxxmaaxxyifmouauibstgpcfwgfmjlfhketkeshfcorqirmssfnbuqiqwqfhbmol",

                        new String[] { // 208 strings x 29 characters
                                "toiscumkhociglkvispihvyoatxcx",
                                "ndojyyephstlonsplrettspwepipw",
                                "yzfkyoqlkrmmfirchzrphveuwmvga",
                                "mxxihihnrfbamcyojqpkzodbejtmm",
                                "fenjcjfdlvcpiatuhjdujhaffqsvq",
                                "ehghndyqjodnnblfwmaygdstotfkv",
                                "heoldutddnksutjakhtghpxxnjykx",
                                "cvrwdewsxdeumhzfrvoilmvksuhyq",
                                "ftqjvzyssocftjwemroghrncynmtc",
                                "idiwclhuepgyynoslhzahtdqwlikt",
                                "eurttrfrmstrbeokzhuzvbfmwywoh",
                                "jxlluilzpysjcnwguyofnhfvhacez",
                                "uskegagtlonducdogwbevugppsptd",
                                "xmcxwufajmnveuwuoyosqnoqwvtjk",
                                "wolpsfxdypmlbjotuxewskisnmczf",
                                "fjryanrmzmpzoefapmnsjdgecrdyw",
                                "jgmxawmndhsvwnjdjvjtxcsjapfog",
                                "wuhkzghvmjhawcfszbhzrbpgsidnb",
                                "yelbldxympctbzfupeocwhkypchuy",
                                "vzduzxudwwqhpftwdspuimioanlzo",
                                "bdpdeofidldoymakfnpgekmsltcrr",
                                "fmyeodowglzyjzuhencufcwdobyds",
                                "dhtypunakzituezjyhbrpuksbamui",
                                "bdmiruibwznqcuczculujfiavzwyn",
                                "eudzjxwbjvagnsjntskmocmpgkybq",
                                "tuynydoakejmwkvojuwbfltqjfgxq",
                                "psrdswqxqsegulcwrwsjnihxedfcq",
                                "cokfdmtsgboidkpgpnmdeyhawkqqs",
                                "fujhvgzdussqbwynylzvtjapvqtid",
                                "rqeuglrsjnmvdsihicsgkybcjltcs",
                                "vhybsbmvymjppfrqmlfrbkpjwpyyy",
                                "aukagphzycvjtvwdhhxzagkevvucc",
                                "hwkduzbxpdhtpvrzrfjndmsqfizmq",
                                "ywnuzzmxeppokxksrfwrpuzqhjgqr",
                                "qbajmepmmizaycwcgmjeopbivsyph",
                                "uamscbxnqnfmmjyehvidnoimmxmtc",
                                "nxvspywfggjrmxryybdltmsfykstm",
                                "amrjbrsiovrxmqsyxhqmritjeauwq",
                                "yorwboxdauhrkxehiwaputeouwxdf",
                                "qkewycsdjglkiwaacdqterkixkgra",
                                "ycngvlvpyvczfxvlwhjgicvempfob",
                                "jgphsxzzqlvujkwwgiodbfjesnbsb",
                                "mkxhemwbbclwdxwgngicplzgajmar",
                                "mryvkeevlthvflsvognbxfjilwkdn",
                                "mezrxffujeysplvavtjqjxsgujqsj",
                                "rtotxqmzxvsqazajvrwsxyeyjteak",
                                "sabctaegttffigupnwgakylngrrxu",
                                "xccuoccdkbboymjtimdrmerspxpkt",
                                "xusnnvngksbjabqjaohdvrniezhmx",
                                "oyuejenqgjheulkxjnqkwvzznricl",
                                "mxszcosgovisnbemrjlndqwkvhqso",
                                "wsgnznrfmxjbdrkwjopylxezxgvet",
                                "dxmisfskvevpcnujqxrqedleuyowk",
                                "dhrgijeplijcvqbormrqglgmzsprt",
                                "vuxchgerokejovrqonxxstibuniki",
                                "lumyzmnzjzhzfpslwsukykwckvkts",
                                "inwkbqmcobubjjpshucechrqrffqs",
                                "ywtxruxokcubekzcrqengviwbtgnz",
                                "ccpnmreqaqjrxwulpunagwxesbila",
                                "pesxtpypenunfpjuyoevzztctecil",
                                "sygfymdcjgvdxutlrhffhnpyjuxmx",
                                "uisdfrvbxzxzhmuektssuktoknkfb",
                                "cejvgynwouzhtfwuuukdbwpmkjrqx",
                                "oudcoagcxjcuqvenznxxnprgvhasf",
                                "sxnlkwgpbznzszyudpwrlgrdgwdyh",
                                "qqbxkaqcyhiobvtqgqruumvvhxolb",
                                "mkhleanvfpemuublnnyzfabtxsest",
                                "bibaxwnriowoavosminabvfxastkc",
                                "bcxgixgrhpfiofpwruzvpqyjzvoll",
                                "lzccnsztxfyqhqyhkuppapvgvdtkm",
                                "pdjkpshvrmqlhindhabubyokzdfrw",
                                "qbbnhwpdokcpfpxinlfmkfrfqrtzk",
                                "rnyelfschnagucguuqqqwitviynry",
                                "qtrjwhrpisocwderqfiqxsdpkphjs",
                                "vxttqosgpplkmxwgmsgtpantazppg",
                                "tyisidnhlksfznubucqxwaheamndj",
                                "kgaqzsckonjuhxdhqztjfxstjvikd",
                                "jeuslzsdwvuoodipdpnlhdihaywzm",
                                "vdzrwwkqvacxwgdhffyvjldgvchoi",
                                "cftbefxgasawzagfugmuthjahylkh",
                                "xraytcolbhkiiasaazkvqzvfxbaax",
                                "oyqtzozufvvlktnvahvsseymtpeyf",
                                "rnnujgyjugrzjoefmghjfhcrnbrtg",
                                "rfzvgvptbgpwajgtysligupoqeoqx",
                                "igbdclqtbikiacwpjrbxhmzejozpy",
                                "dyzwwxgdbeqwlldyezmkopktzugxg",
                                "hmetreydbcstkwoexwsfhfekfvfpl",
                                "zcnftuzrvzjjudsgcqmmfpnmyrenu",
                                "zzmvkskzeglxaqrrvmrgcwcnvkhwz",
                                "vjswvekfyqhjnsusefdtakejxbejr",
                                "rwwzwbcjwiqzkwzfuxfclmsxpdyvf",
                                "fdbdychmupcsxvhazvrihhnxfyumo",
                                "vdtevyducpdksntgyaqtkrrkwiyuh",
                                "nbvqeyoghccxfuwacxzxqkezxefxa",
                                "vpgbefpqpsjmdecmixmmbsjxzwvjd",
                                "jwgqmsvhnykclexepxqxqzghwfxfd",
                                "olyfxbvdrspxqnxnuoygkruczddgs",
                                "qgmxtdfoiaakorebqpbbpegawrqym",
                                "liaivbhcgvjjnxpggrewglalthmzv",
                                "choncklguqgnyrcslwztbstmycjzi",
                                "fpkdpenxlewyxxgrkmwrmshhzfnor",
                                "hhhcaqxbqpthuaafwgrouaxonzocl",
                                "ipahojoysepzhpljpaugrghgjimtd",
                                "wosrmnouwpstgbrvhtlqcnmqbygbf",
                                "nwyskffpxlragrnfffawqtgyfpmzx",
                                "bcvvadhnssbvneecglnqxhavhvxpk",
                                "hoavxqksjreddpmibbodtbhzfehgl",
                                "lazxadnftllhmjslfbrtdlahkgwle",
                                "uuukupjmbbvshzxyniaowdjamlfss",
                                "tpqtazbphmfoluliznftodyguessh",
                                "ychqumiscfkwmqqxunqrfbgqjdwmk",
                                "rkdclgzjvqrjofjjvbyfragofeoaz",
                                "pphhedxdepgfgrqerpuhgmaawhnhq",
                                "cacrsvutylalqrykehjuofisdookj",
                                "kyldfriuvjranikluqtjjcoiqffdx",
                                "bnwvrwgoskzqkgffpsyhfmxhymqin",
                                "uzmlliugckuljfkljoshjhlvvlnyw",
                                "abfxqbdqnexvwsvzvcsbrmkbkuzsd",
                                "xotbbyvxyovzxgtcyzgqnsvcfhczo",
                                "bwtpqcqhvyyssvfknfhxvtodpzipu",
                                "nsfbpjqkijvudpriqrfsrdfortimg",
                                "tgwyqugeuahpuvvzmgarbsyuutmbx",
                                "upnwqzbsazplkyaxqorqsshhlljjl",
                                "edfyahijobxyhimebctobsjudkqst",
                                "ialhfmgjohzoxvdaxuywfqrgmyahh",
                                "jlhcpegmtrelbosyajljvwwedtxbd",
                                "tpfppjzowoltyqijfoabgzejerpat",
                                "mgogyhzpmsdemugqkspsmoppwbnwa",
                                "nubmpwcdqkvhwfuvcahwibniohiqy",
                                "ukfadjvdnrievszilfinxbyrvknfi",
                                "dgnepdiimmkcxhattwglbkicvsfsw",
                                "syqxmarjkshjhxobandwyzggjibjg",
                                "bnwxjytnaejivivriamhgqsskqhnq",
                                "hzyjdcbyuijjnkqluaczrnrbbwaee",
                                "yscnqoohcsxenypyqhfklloudgmkl",
                                "habidqszhxorzfypcjcnopzwigmbz",
                                "wjdqxdrlsqvsxwxpqkljeyjpulbsw",
                                "tytawuuyjrwxboogfessmltwdcssd",
                                "pfixglatdvuogdoizdtsgsztsfcih",
                                "apkvhvsqojyixaechvuoemmyqdlfk",
                                "ouaehwnnxwkdplodpuqxdbemfwahp",
                                "ixuckaralemvsnbgooorayceuedto",
                                "ymxdjrqikughquwtenyucjdgrmipi",
                                "smrwrlkvpnhqrvpdekmtpdfuxzjwp",
                                "bhjakgajafgzxpqckmhdbbnqmcszp",
                                "beqsmluixgsliatukrecgoldmzfhw",
                                "greuevnjssjifvlqlhkllifxrxkdb",
                                "yzsqcrdchhdqprtkkjsccowrjtyjj",
                                "sviyovhitxeajqahshpejaqtcdkuv",
                                "qtwomymjskujjtmxiueopwacrwfuq",
                                "mzyjtctvtwgyiesxhynvogxnjdjph",
                                "dyfbxcaypyquodcpwxkstbthuvjqg",
                                "hfmflesfabvanxlrurjtigkjotftq",
                                "mxydechlraajjmoqpcyoqmrjwoium",
                                "nabesvshjmdbhyhirfrkqkmfwdguj",
                                "bhrfxxemhgbkgmkhjtkzyzdqmxxwq",
                                "gziobrjeanlvyukwlscexbkibvdjh",
                                "mcwwubbnwenybmfqglaceuyqnoadz",
                                "xyzvyblypeongzrttvwqzmrccwkzi",
                                "ncfalqenfcswgerbfcqsapzdtscnz",
                                "dtqpezboimeuyyujfjxkdmbjpizpq",
                                "wmuhplfueqnvnhukgjarxlxvwmriq",
                                "qwapdkoqswyclqyvbvpedzyoyedvu",
                                "uoqbztnftzgahhxwxbgkilnmzfydy",
                                "zsddaahohbszhqxxgripqlwlomjbw",
                                "bwadkiavdswyuxdttoqaaykctprkw",
                                "eixdbntdfcaeatyyainfpkclbgaaq",
                                "nmjnpttflsmjifknezrneedvgzfmn",
                                "avlzyhfmeasmgrjawongccgfbgoua",
                                "kklimhhjqkmuaifnodtpredhqygme",
                                "xzbwenvteifxuuefnimnadwxhruvo",
                                "ugmwlmidtxkvqhbuaecevwhmwkfqm",
                                "rhpyjfxbjjryslfpqoiphrwfjqqha",
                                "eeaipxrokncholathupdetgaktmvm",
                                "ltuimrnsphqslmgvmmojawwptghon",
                                "azitvyhvlspvoaeipdsjhgyfjbxhi",
                                "efrelxezcgikdliyhvpocvvpkvagv",
                                "znxforctwzecxyrkwufpdxadrgzcz",
                                "kcqgynjcpbylayvgdqfpbqmshksyf",
                                "hrljvedsywrlyccpaowjaqyfaqioe",
                                "cjmfyvfybxiuqtkdlzqedjxxbvdsf",
                                "zeqljuypthkmywaffmcjkickqqsuh",
                                "wnfzoyvkiogisdfyjmfomcazigukq",
                                "zyaaqxorqxbkenscbveqbaociwmqx",
                                "ahnpivdtlcnptnxjyiaafislqavam",
                                "edtqirqmjtvsfhadhafktyrmkzmvi",
                                "wponuefgdtcrgxswiddygeeflpjee",
                                "xozgwhtbhlkvrzismnozqpfthajaf",
                                "ptnfnojnlinbfmylhdlijcvcxzjhd",
                                "uxekzlgigjpsukjvsdihrjzgovnre",
                                "rbohxlytsmoeleqrjvievpjipsgdk",
                                "fxtzaxpcfrcovwgrcwqptoekhmgpo",
                                "tvxvvgjbyxpgwpganjiaumojpyhhy",
                                "vqjjhfaupylefbvbsbhdncsshmrhx",
                                "urhedneauccrkyjfiptjfxmpxlssr",
                                "ltvgknnlodtbhnbhjkmuhwxvzgmkh",
                                "ucztsneqttsuirmjriohhgunzatyf",
                                "rbzryfaeuqkfxrbldyusoeoldpbwa",
                                "atlgpnkuksuesrduxkodwjzgubpsm",
                                "lrdniqbzxrbpcvmzpyqklsskpwctg",
                                "qvnvgzkyhistydagsgnujiviyijdn",
                                "uzatydzcnktnkeyztoqvogodxxznh",
                                "ocbvphmtpwhcgjbnmxgidtlqcnnwt",
                                "koudovxrjkusxdazxaawmvoostlvv",
                                "ptruqmjtbaapgmkfnbwnlvzlxwdpz",
                                "xdxtpbpoemekvxzrrakwjxcxqsdas",
                                "gdpclnsguabtgbfwdmrmbvydorfrb",
                                "htwxdbarwuxykgduxjlkxppwyruih"
                        },
                        List.of(373))
        );
    }

}

